services:
  api:
    container_name: api
    build:
      context: api
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - MODEL_SERVER_URL=http://model-server:3000

  model-server:
    container_name: model-server
    build:
      context: .
      dockerfile: model_server.Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow_server:5000

networks:
  recsys-mvp:
    external: true
