services:
  api:
    container_name: api
    build:
      context: api
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - REDIS_HOST=kv_store
      - I2V_MODEL_SERVER_URL=http://i2v_model_server:3000
      - SEQRP_MODEL_SERVER_URL=http://seqrp_model_server:3000
      - FEAST_ONLINE_SERVER_HOST=feature_online_server
    volumes:
      - ./api:/app/
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  i2v_model_server:
    container_name: i2v_model_server
    build:
      context: .
      dockerfile: model_server.Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow_server:5000
    entrypoint: ["bentoml", "serve", "service:I2VService"]

  seqrp_model_server:
    container_name: seqrp_model_server
    build:
      context: .
      dockerfile: model_server.Dockerfile
    ports:
      - "3001:3000"
    env_file:
      - .env
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow_server:5000
    entrypoint: ["bentoml", "serve", "service:SeqRPService"]

networks:
  recsys-mvp:
    external: true
