services:
  postgres:
    container_name: postgres
    image: postgres
    env_file:
      - .env
    environment:
      PGDATA: /data/postgres
    volumes:
       - ./db:/data/postgres
       # Run scripts to create schemas upon startup
       - ./init-db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
