
version: 2

models:
  - name: user_rating_stats
    description: "Statistics of user-asin rating"
    data_tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - user_id
            - timestamp
  - name: item_rating_stats
    description: "Statistics of asin rating"
    data_tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - parent_asin
            - timestamp
